default_environment: default
environments:
    default:
        connections:
            duckdb:
                - name: duckdb-default
                  path: jaffle_shop.duckdb
            chess:
                - name: chess-default
                  players:
                    - MagnusCarlsen
                    - Hikaru
